CREATE TABLE BUSINESS(
    BUSINESS_ID VARCHAR(50) PRIMARY KEY,
    FULL_ADDRESS VARCHAR(300) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    REVIEW_COUNT NUMBER(10) NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    STARS NUMBER(2,1) NOT NULL
);

CREATE TABLE CATEGORIES(
    BUSINESS_ID VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    PRIMARY KEY(BUSINESS_ID, CATEGORY),
    FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID) ON DELETE CASCADE
);

CREATE TABLE SUB_CATEGORIES(
    BUSINESS_ID VARCHAR(50) NOT NULL,
    SUB_CATEGORY VARCHAR(50) NOT NULL,
    PRIMARY KEY(BUSINESS_ID, SUB_CATEGORY),
    FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID) ON DELETE CASCADE
);

CREATE TABLE ATTRIBUTES(
    BUSINESS_ID VARCHAR(50) NOT NULL,
    ATTRIBUTE VARCHAR(50) NOT NULL,
    PRIMARY KEY(BUSINESS_ID, ATTRIBUTE),
    FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID) ON DELETE CASCADE
);

CREATE TABLE USERS(
    USER_ID VARCHAR(50) PRIMARY KEY,
    YELPING_SINCE DATE NOT NULL,
    REVIEW_COUNT NUMBER(10) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    AVERAGE_STARS NUMBER(20,16) NOT NULL,
    VOTE_COUNT NUMBER(10) NOT NULL,
    NUMBER_FRIEND NUMBER(10) NOT NULL
);

CREATE TABLE REVIEW(
    REVIEW_ID VARCHAR(50) PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    BUSINESS_ID VARCHAR(50) NOT NULL,
    STAR NUMBER(1) NOT NULL,
    R_DATE DATE NOT NULL,
    TEXT LONG,
    VOTE_COUNT NUMBER(10) NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID) ON DELETE CASCADE
);

CREATE TABLE CHECKIN(
    BUSINESS_ID VARCHAR(50),
    DAYTIME VARCHAR(4) NOT NULL,
    COUNT NUMBER(10) NOT NULL,
    PRIMARY KEY(BUSINESS_ID, DAYTIME),
    FOREIGN KEY(BUSINESS_ID) REFERENCES BUSINESS(BUSINESS_ID) ON DELETE CASCADE
);
